name: Python package

on:
  push:
    tags:
      - v*
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/whiscraper
    permissions:
      id-token: write
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Build package
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
